#!/bin/bash

function run_help() {

cat <<EOT
Dotfiles - Ryan Domingue - http://ryandomingue.com/

Usage: $(basename "$0") [options]

Options:
    -h, --help      Print this help text
    --copy          Copy the files in place instead of linking
                    (gitconfig is always copied)
                    ** "Copy mode" also suppresses initiallizing a Git repo and pulling updates from Github **
    --no-packages   Suppress package installations and updates (including casks)

Documentation can be found at https://github.com/goodguyry/dotfiles

Copyright (c) Ryan Domingue
Licensed under the MIT license.
EOT

}