#!/bin/bash

# git branch ahead/behind another.
function gcheck() {
  # use first argument or master.
  local ORIGINAL=${1-master};

  # use the second argument or current branch if not given.
  local CURRENT="$(git branch | grep \* | sed s/\*\ //)";
  local COMPARE=${2-$CURRENT};

  # run git rev-list and capture numbers returned.
  local RESULT="$(git rev-list --left-right --count ${ORIGINAL}...${COMPARE})";

  local NUMBERS=(${RESULT});
  printf '\n';
  # print numbers in a pretty message.
  if [ ${NUMBERS[0]} -gt 0 ]; then
    echo -e "${ORANGE}- ${COMPARE} is ${NUMBERS[0]} commits behind ${ORIGINAL}${RESET}";
  fi;
  if [ ${NUMBERS[1]} -gt 0 ]; then
    echo -e "${YELLOW}+ ${COMPARE} is ${NUMBERS[1]} commits ahead of ${ORIGINAL}${RESET}";
  fi;
}
