#!/bin/bash

# Compare original and gzipped file size.
function gz() {
  local ORIGSIZE=$(wc -c < "${1}");
  local GZIPSIZE=$(gzip -c "${1}" | wc -c);
  local RATIO=$(echo "${GZIPSIZE} * 100/ ${ORIGSIZE}" | bc -l);
  printf "orig: %d bytes\n" "${ORIGSIZE}";
  printf "gzip: %d bytes (%2.2f%%)\n" "${GZIPSIZE}" "${RATIO}";
}
