#!/bin/bash

##
# Change to a given project directory.
# If no PROJECTNAME is passed, change to ~/Projects.
#
# Usage: p [-o] PROJECTNAME
#   -o  Open the project directory in your editor and git client.
##
function p() {
  # Check for passed argument(s).
  if [[ ${#} -gt 0 ]]; then
    local OPEN=false;

    # Test for option(s)
    for OPT in "${@}"; do
      case "${OPT}" in
        -o) OPEN=true ;;
         *) DIR="${OPT}" ;;
      esac
    done

    FIND_ARGS="-maxdepth 1 -mindepth 1 -type d -name ${DIR} -print -quit";

    local SITE=$(find "${HOME}"/Projects/sites $FIND_ARGS);
    local PROJECT=$(find "${HOME}"/Projects $FIND_ARGS);

    # Change to the project root.
    if [[ -n "${PROJECT}" ]]; then
      cd "${PROJECT}";
    elif [[ -n "${SITE}" ]]; then
      cd "${SITE}";
    else
      echo "\"${DIR}\" not found.";
      return;
    fi

    if $OPEN; then
      # Open the project root in the editor
      if [[ "$(type -P subl)" ]]; then
        SUBLIME_WORKSPACE=$(find . -type f -name "*.sublime-workspace");
        subl $([[ -r "${SUBLIME_WORKSPACE}" ]] && echo "${SUBLIME_WORKSPACE}" || echo '.');
      fi

      # Open the project in the git client
      [[ "$(type -P smerge)" ]] && smerge .;
    fi
  else
    # No arguments; change to $HOME/Projects.
    cd "${HOME}/Projects";
  fi;
}
