#!/bin/bash

##
# Add a timestamp to a file or folder; optionally copy the timestamp to the clipboard.
#
# Usage: stamp [-d] string
#
#   -d (optional) : duplicate item before appending the timestamp
#   -c (optional) : copy the timestamp to the clipboard
#   -s=SEPARATOR (optional) : set the separator between the item name and the timestamp
#
# Change date format in $stamp to alter output.
##

function run_stamp_help() {

cat <<EOT
Usage: stamp [-d] [-c] [-s=SEPARATOR]

Options:
    -h, --help        Print this help text
    -d                Duplicate the item before appending the timestamp
    -c                Copy the timestamp to the clipboard
    -s=SEPARATOR      Define the separator between the itme name and the timestamp
EOT
}

function stamp() {
  # Help text
  if [[ "${1}" == "-h" || "${1}" == "--help" ]]; then
    run_stamp_help;
    return;
  fi;

  local ERRORMSG='Error: A file or folder is required for timestamping';
  local STAMP="$(date +%Y%m%d_%H%M%S)";
  local DUP=false;
  local CLIPBOARD=false;
  local SEP=${STAMP_SEPARATOR:="."}; # Default separator

  # No args were given.
  if [[ ${#} -lt 1 ]]; then
    run_stamp_help;
    return;
  fi;

  # Test for flags.
  for OPT in "${@}"; do
    case "${OPT}" in
      -d) DUP=true ;;              # Duplicate the item before appending the timestamp.
      -c) CLIPBOARD=true ;;        # Copy the timestamp to the clipboard.
      -s*) SEP="${OPT##*-s=}" ;;   # Set the separator between the itme name and the timestamp.
      *) ITEM="${OPT}" ;;          # Set ITEM to the other argument.
    esac
  done;

  # Copy the timestamp to the clipboard and exit.
  if $CLIPBOARD; then
    $(echo "${STAMP}" | pbcopy);
    echo "${STAMP} copied to the clipboard.";
    # Exit if there's no file/directory passed.
    if [[ -z "${ITEM}" ]]; then
      return;
    fi;
  fi;

  # Make sure ITEM is set before proceeding.
  if [[ -z "${ITEM}" ]]; then
    run_stamp_help;
    return;
  fi;

  if [[ -d "${ITEM}" ]]; then
    # Split off the trailing slash (if it's there).
    NAME="${ITEM%/*}";
    # Clear the extension.
    EXT="";
  else
    # Split the name from the extension.
    NAME="${ITEM%.*}";
    # Include the dot in the extension to make things easier in the next step.
    EXT=".${ITEM##*.}";
  fi

  if $DUP; then
    # Duplicate the item with timestamp.
    cp -r "${NAME}"{,"${SEP}${STAMP}"}"${EXT}";
  else
    # Timestamp the item without duplication.
    mv "${NAME}"{,"${SEP}${STAMP}"}"${EXT}";
  fi;

  unset SEP;
}
