#!/bin/bash

# Navigation
alias ..='cd ..';
alias ...='cd ../..';
alias ....='cd ../../..';
alias ~='cd ~';
alias -- -='cd -';

# Shortcuts
alias db='cd ~/Dropbox';
alias dl='cd ~/Downloads';
alias dk='cd ~/Desktop';
alias s='cd ~/Sites';
alias g='git';
alias j='jekyll';
alias js='jekyll serve --watch';
alias v='vagrant';
alias o='open';
alias oo='open .';
alias list="ls -l";

# Enable aliases to be sudo’ed.
alias sudo='sudo ';

# Reload the shell (i.e. invoke as a login shell).
alias reload='clear && exec $SHELL -l';

# Formatting

# Print each PATH entry on a separate line.
alias path='echo -e ${PATH//:/\\n}';

# Detect which `ls` flavor is in use.
if ls --color > /dev/null 2>&1; then # GNU `ls`
  colorflag='--color';
else # macOS `ls`
  colorflag='-G';
fi;

# List all files colorized in long format.
alias l="ls -lF ${colorflag}";

# List all files colorized in long format, including dot files.
alias la="ls -laF ${colorflag}";

# List only directories.
alias lsd="ls -lF ${colorflag} | grep --color=never '^d'";

# Always use color output for `ls`.
alias ls="command ls ${colorflag}";

# Always enable colored `grep` output.
alias grep='grep --color=auto';
alias fgrep='fgrep --color=auto';
alias egrep='egrep --color=auto';

# Cleanup

# Flush Directory Service cache.
alias flush='sudo discoveryutil mdnsflushcache && sudo discoveryutil udnsflushcaches;';

# Update installed Ruby gems, Homebrew, npm, and their installed packages.
alias update='brew update; brew upgrade; brew cleanup; \
  brew upgrade brew-cask; brew cask cleanup; \
  nvm install node --reinstall-packages-from=$(nvm current | sed "s/v//") \
  npm update -g \
  rvm cleanup all; \
  sudo gem update --system; sudo gem update; sudo gem cleanup';

# Clean up LaunchServices to remove duplicates in the “Open With” menu.
LSREG='/System/Library/Frameworks/CoreServices.framework/Frameworks/LaunchServices.framework/Support/lsregister';
alias lscleanup="${LSREG} -kill -r -domain local -domain system -domain user && killall Finder";

# Empty the Trash on all mounted volumes and the main HDD.
# Also, clear Apple’s System Logs to improve shell startup speed.
alias emptytrash='sudo rm -rfv /Volumes/*/.Trashes; sudo rm -rfv ~/.Trash; sudo rm -rfv /private/var/log/asl/*.asl';

# Secure empty the Trash on all mounted volumes and the main HDD.
alias secempty='sudo srm -rvzf /Volumes/*/.Trashes; sudo srm -rvzf ~/.Trash';

# Clean out Launchpad.
alias lpclean="sqlite3 ~/Library/Application\ Support/Dock/*.db \"DELETE from apps; DELETE from groups WHERE title<>''; DELETE from items WHERE rowid>2;\"; Killall Dock";

# Rebuild Launchpad.
alias lpreset='rm ~/Library/Application\ Support/Dock/*.db; killall Dock';

# Helpers

# URL-encode strings.
alias urlencode='python -c "import sys, urllib as ul; print ul.quote_plus(sys.argv[1]);"';

# One of @janmoesen’s ProTip™s.
for METHOD in GET HEAD POST PUT DELETE TRACE OPTIONS; do
  alias "${METHOD}"="lwp-request -m '${METHOD}'";
done;

# Show/hide hidden files in Finder.
alias show='defaults write com.apple.finder AppleShowAllFiles -bool true && killall Finder';
alias unshow='defaults write com.apple.finder AppleShowAllFiles -bool false && killall Finder';

# Hide/show all desktop icons (useful when presenting).
alias hidedesktop='defaults write com.apple.finder CreateDesktop -bool false && killall Finder';
alias showdesktop='defaults write com.apple.finder CreateDesktop -bool true && killall Finder';

# Disable Spotlight.
alias spotoff='sudo mdutil -a -i off';
# Enable Spotlight.
alias spoton='sudo mdutil -a -i on';

# Stopwatch
alias timer='echo "Timer started. Stop with Ctrl-D." && date && time cat && date';

# Canonical hex dump; some systems have this symlinked.
command -v hd > /dev/null || alias hd="hexdump -C";

# macOS has no `md5sum`, so use `md5` as a fallback.
command -v md5sum > /dev/null || alias md5sum="md5";

# macOS has no `sha1sum`, so use `shasum` as a fallback.
command -v sha1sum > /dev/null || alias sha1sum="shasum";

# IP addresses
alias ip='dig +short myip.opendns.com @resolver1.opendns.com';
alias localip='ipconfig getifaddr en0';
alias ips="ifconfig -a \ | \
  grep -o 'inet6\? \(\([0-9]\+\.[0-9]\+\.[0-9]\+\.[0-9]\+\)\|[a-fA-F0-9:]\+\)' \ | \
  sed -e 's/inet6* //'";

# Mac address
alias mac='ifconfig en1 | grep ether';
