#!/bin/bash

# Make vim the default editor.
export EDITOR='vim';

# Don't clear the screen after quitting a manual page.
export MANPAGER='less -X';
# Highlight section titles in manual pages.
export LESS_TERMCAP_md="${YELLOW}";

# Larger bash history (allow 32³ entries; default is 500).
export HISTSIZE=32768;
export HISTFILESIZE="${HISTSIZE}";
# Ignore duplicates and commands that begin with a space.
export HISTCONTROL='ignoreboth';

# Make some commands not show up in history.
export HISTIGNORE='cd*:cd -:pwd;exit:date:* --help:ssh *:open*:oo*';

# Timestamps for bash history.
# https://debian-administration.org/users/rossen/weblog/1
HISTTIMEFORMAT='%F %T ';
export HISTTIMEFORMAT;

# Prefer US English and use UTF-8.
export LANG='en_US';
export LC_ALL='en_US.UTF-8';

# Colon-separated list of directories in which the shell looks for destination directories specified by the cd command.
CDPATH='.:~:/private';

# Enable some Bash 4 features when possible:
# * `autocd`, e.g. `**/qux` will enter `./foo/bar/baz/qux`
# * Recursive globbing, e.g. `echo **/*.txt`
for OPTION in autocd globstar; do
  shopt -s "${OPTION}" 2> /dev/null;
done;

# Case-insensitive globbing (used in pathname expansion).
shopt -s nocaseglob;

# Append to the Bash history file, rather than overwriting it.
shopt -s histappend;

# Autocorrect typos in path names when using `cd`.
shopt -s cdspell;
