#!/bin/bash

# Brew paths
PATH=/usr/local/bin:/usr/local/sbin;

# $HOME/.nvm/versions/node/{version}/bin
PATH="${PATH}:${NVM_BIN}";

# Add RVM to PATH for scripting.
PATH="${PATH}:${HOME}/.rvm/bin";

# Home bin
PATH="${PATH}:${HOME}/.bin";

# Add back default bins.
PATH="${PATH}:/usr/bin:/bin:/usr/sbin:/sbin";

if [ "$(type -P brew)" ]; then
  COREUTILS="$(brew --prefix coreutils)";

  if [[ "${COREUTILS}" ]]; then
    # Add brew-installed GNU core utilities bin.
    PATH="${PATH}:${COREUTILS}/libexec/gnubin";
    # Add coreutils man pages.
    MANPATH="${COREUTILS}/libexec/gnuman:${MANPATH}";
  fi;
else
  # Fall back to macOS default.
  PATH="${PATH}:/libexec/gnubin";
fi;

# Add MySQL.
PATH="${PATH}:/usr/local/mysql/bin";

export PATH;
export MANPATH;
