#!/bin/bash

# Brew paths
PATH=/usr/local/bin:/usr/local/sbin;

# $HOME/.nvm/versions/node/{version}/bin
PATH=${PATH}:${NVM_BIN};

# Add RVM to PATH for scripting
PATH=${PATH}:${HOME}/.rvm/bin;

# Home bin
PATH=${PATH}:${HOME}/.bin;

# Add back default bins
PATH=${PATH}:/usr/bin:/bin:/usr/sbin:/sbin;

# Add brew-installed GNU core utilities bin
if [ "$(type -P brew)" ] && [[ "$(brew --prefix coreutils)" ]]; then
  PATH=${PATH}:"$(brew --prefix coreutils)/libexec/gnubin";
else
  # Fall back to OS X default
  PATH=${PATH}:/libexec/gnubin;
fi;

# Add MySQL
PATH=${PATH}:/usr/local/mysql/bin;

# Add VS Code
PATH="${PATH}:/Applications/Visual Studio Code.app/Contents/Resources/app/bin"

export PATH;

# Add coreutils man pages
if [ "$(type -P brew)" ] && [[ "$(brew --prefix coreutils)" ]]; then
  MANPATH="$(brew --prefix coreutils)/libexec/gnuman:${MANPATH}"
fi;

export MANPATH;
