#!/bin/bash

export INPUTRC="${HOME}/.inputrc";

# Load the shell dotfiles, and then some:
# Shamelessly stolen from @wilto
declare -a FILES=(
  "${HOME}/.nvm/nvm.sh" # Load NVM.
  "${HOME}/.prompt" # Custom bash prompt.
  "${HOME}/.bash_config" # Configuration.
  "${HOME}/.aliases" # Aliases.
  "${HOME}/.functions" # Functions.
  "${HOME}/.paths" # Path modifications.
  "${HOME}/.dotfiles.local" # Local and private settings not under version control (e.g. git name/email, package lists).
  "${HOME}/.rvm/scripts/rvm" # Load RVM into a shell session *as a function*.
);

# If these files are readable, source them.
for INDEX in ${!FILES[*]}; do
  if [[ -r "${FILES[$INDEX]}" ]]; then
    source "${FILES[$INDEX]}";
  fi;
done;

unset FILES;

source <(npm completion);

# Environment variables.
GIT_COMMITTER_NAME="$(git config user.name)";
GIT_COMMITTER_EMAIL="$(git config user.email)";

# Current Node version.
NVM_CURRENT="$(nvm current | sed 's/v//')";
