#!/bin/bash

# ----------------------------------------------
# Create a new file and open it in a text editor
#
# 	Uses EDITOR defined in .bashrc
#
# 	Usage: nf string1 [string2]
#
#		string1 : A string representing the new file's name. Can be entered
#							with or without the file extension, or as the extension
#							(with the preceeding '.'). When the name or extension are
#							not provided, the default name and extension is used.
#
#							Examples: nf name			 ->  name.[$ext]
#												nf name.ext	 ->	 name.ext
#												nf .ext			 ->	 [$name].ext
#
#		string2 : The new file's extension, separated from the name by a space.
#
#							Example:  nf name ext	 ->	 name.ext
#
#		To change the default filename, change $defaultpre
#		To change the default filetype, change $ext
# ----------------------------------------------

function nf_orig() {
	# declared in this manner so it only has to be updated in one place
	defaultpre=$(date +%y%j%H%M%S)

	# default name & ext
	name=$defaultpre
	ext="md"

	# there are args... 
	if [ $# -gt 0 ]; then

		name="$1"

		# entire filename.ext was entered
		if [[ "$1" == *.* ]]; then
			name=$(echo "$1" | cut -f 1 -d '.')
			ext=$(echo "$1" | cut -f 2 -d '.')
		fi

		# two args, separated by a space
		if [ $# -gt 1 ]; then ext="$2"; fi

	fi
	
	# if ".ext" was entered as the only arg, reset default name
	if [ -z "$name" ]; then name="$defaultpre"; fi

	# create the file and open it
  filename="$name.$ext"
	echo "$filename"
  touch $filename
  open -a "$EDITOR" $filename
}
