#!/bin/bash
#
# Copyright (c) 2024 Ryan Domingue and contributors
# Report bugs at: https://github.com/goodguyry/dotfiles/issues
#
# This is free software with ABSOLUTELY NO WARRANTY.

source "${HOME}/.dotfiles/lib/mkdirs";
source "${HOME}/.dotfiles/lib/setfile";
source "${HOME}/.dotfiles/lib/status";

# @todo Confirm.

# @todo Print script details.

status --info "Symlinking files to ${HOME}...";

declare -a home_files=(
  'home/aliases'
  'home/bash_config'
  'home/bashrc'
  'home/completions'
  'home/hushlogin'
  'home/inputrc'
  'home/paths'
  'home/profile'
  'home/prompt'
  'home/vimrc'
);

# Link home dotfiles files.
for home_file in "${home_files[@]}"; do
  [[ -f "${home_file}" ]] && setfile "${home_file}" "${HOME}/.$(basename $home_file)";
done;

# Link function files.
mkdirs "${HOME}/.functions";
if [[ $? ]]; then
  for function_file in home/functions/*; do
    [[ -f "${function_file}" ]] && setfile "${function_file}" "${HOME}/.functions/$(basename $function_file)";
  done;
else
  status --error "Could not create ${HOME}/.functions"
fi

# Link commands into PATH.
for bin_file in home/bin/*; do
  [[ -f "${bin_file}" ]] && setfile "${bin_file}" "${HOME}/.bin/$(basename $bin_file)";
done;

# Always copy editorconfig (can't remember why).
rsync -avz --quiet 'home/editorconfig' "${HOME}/.editorconfig";

# Create dotfiles.local if not present.
if [[ ! -r "${HOME}/.dotfiles.local" ]]; then
  status --info "Creating ${HOME}/.dotfiles.local";
  printf '#!/bin/bash\n\n' >> "${HOME}/.dotfiles.local";
fi;

# Source bashrc to make sure the environment is set before moving on.
source "${HOME}/.bashrc";
status --success "Done.";

# @todo Support subcommands: packages, apps, run prefs.
# ! [ -z "$(type -P git)" ] && install-git;
