#!/bin/bash

DOTFILES_DIRECTORY="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )";
DOTFILES_GIT_REMOTE="https://github.com/goodguyry/dotfiles"


# Helper functions
source "$DOTFILES_DIRECTORY/lib/help";
source "$DOTFILES_DIRECTORY/lib/utils";


# Help text
if [[ "$1" == "-h" || "$1" == "--help" ]]; then
  run_help;
  exit;
fi;


# Test for known flags
for opt in $@;
do
  case $opt in
    --no-packages)  NO_PACKAGES=true ;;               # Suppresses installing packages
               -n)  NO_PACKAGES=true ;;
           --copy)  COPY_FILES=true ;;                # Copy files instead of linking
               -c)  COPY_FILES=true ;;
         --server)  SERVER=true; NO_PACKAGES=true ;;  # Skip OS X-related packages/settings
               -s)  SERVER=true; NO_PACKAGES=true ;;
           -*|--*)  e_warning "Warning: invalid option $opt" && run_help && exit ;;
  esac
done;


# Create a Projects folder
if [[ ! $SERVER ]]; then
  mkdirs "$HOME/Projects";
fi;


# Create a ~/.bin directory, if it doesn't exist
mkdirs "$HOME/.bin";


# Conditionally install Command Line Tools, Homebrew and Git
if [[ $NO_PACKAGES ]]; then
  e_header "Skipping Homebrew and Git installations.";
else
  # Before relying on Homebrew, check that packages can be compiled
  if ! type_exists 'gcc'; then
    e_error "The XCode Command Line Tools must be installed first.";
    xcode-select --install;
  fi;

  # Check for Homebrew
  if ! type_exists 'brew'; then
    e_header "Installing Homebrew...";
    ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)";
    brew doctor;
    [[ $? ]] && e_success "Homebrew installed.";
  fi;

  # Check for git
  if ! type_exists 'git'; then
    e_header "Updating Homebrew...";
    brew update;
    e_header "Installing Git...";
    brew install git;
    ln -sf "$(brew --prefix)/share/git-core/contrib/diff-highlight/diff-highlight" "$HOME/.bin/diff-highlight";
  fi;
fi;


# Conditionally init and pull the Git repo
if [[ ! $COPY || ! $SERVER ]] && type_exists 'git' ; then
  cd "$DOTFILES_DIRECTORY";
  # Initialize the git repository if it's missing
  if ! is_git_repo; then
    e_header "Initializing git repository...";
    git init;
    git remote add origin $DOTFILES_GIT_REMOTE;
    git fetch origin master;
    # Reset the index and working tree to the fetched HEAD
    git reset --hard FETCH_HEAD;
    # Remove any untracked files
    git clean -fd;
    e_header "Syncing dotfiles...";
    # Pull down the latest changes
    git pull --rebase origin master;
  else
    e_header "Already a Git repo.";
  fi;
else
  e_header "Skipping 'git init'";
fi;


# Sets the dotfiles in place in the `HOME` directory.
function set_files() {
  e_header "Setting files...";

  # A list of needed directories
  declare -a DIRECTORIES=(
    $HOME/.functions
    $HOME/.vim
    $HOME/.vim/backups
    $HOME/.vim/swaps
  );

  # Create directories if they don't exist
  for DIRECTORY in ${DIRECTORIES[*]}; do
    mkdirs ${DIRECTORY};
  done;

  # Copy `.gitconfig`
  rsync -avz --quiet "dev/gitconfig" "$HOME/.gitconfig";

  # Download the Solarized Vim theme
  # But check for it first
  if [[ ! -r "$HOME/.vim/colors/solarized.vim" ]]; then
    if [[ $SERVER ]]; then
      # Extract colors/solarized.vim into .vim (Linux-friendly)
      e_header "Downloading Solarized Vim theme...";
      curl -#L https://github.com/altercation/vim-colors-solarized/tarball/master | tar -xzv -C "$HOME/.vim" --strip-components 1 --wildcards **/solarized.vim;
    else
      # Extract colors/solarized.vim into .vim (OS X-Friendly)
      e_header "Downloading Solarized Vim theme...";
      curl -#L https://github.com/altercation/vim-colors-solarized/tarball/master | tar -xzv -C "$HOME/.vim" --strip-components 1 --include="**/solarized.vim";
    fi;
    [[ $? ]] && e_success "Solarized theme installed";
  else
    e_header "Solarized theme already installed.";
  fi;

  # Files and folders not to be linked/copied
  declare -a EXCLUDED_FILES=(
    dev/gitconfig # Already copied
    shell/
    shell/functions
  );

  # Strip the shell and dev directories from the path before setting these files
  dotfiles dev/* shell/* shell/**/* --strip-dir;

  # Set Sublime Text settings
  SUBLIME_TEXT_USER="$HOME/Library/Application Support/Sublime Text 3/Packages/User";
  ln -fs "$DOTFILES_DIRECTORY/etc/Markdown.sublime-settings"     "$SUBLIME_TEXT_USER/Markdown.sublime-settings";
  ln -fs "$DOTFILES_DIRECTORY/etc/Preferences.sublime-settings"  "$SUBLIME_TEXT_USER/Preferences.sublime-settings";
  ln -fs "$DOTFILES_DIRECTORY/etc/Ruby.sublime-settings"         "$SUBLIME_TEXT_USER/Ruby.sublime-settings";

  [[ $? ]] && e_success "Dotfiles update complete!";
}


# Ask before potentially overwriting files
printf "\n";
e_warning "Warning: This step may overwrite your existing dotfiles.";
printf "Continue? [Y/n]";
read CONTINUE;
printf "\n";


# Conditionally set the dotfiles in place
if [[ "$CONTINUE" == "n" ]]; then
  e_header "Aborting...";
  exit 1;
else
  set_files;
fi;


# Create dotfiles.local if not present
[[ -r "$HOME/.dotfiles.local" ]] && printf "#!/bin/bash\n\n" >> "$HOME/.dotfiles.local";


# Source dotfiles.local in case it contains Git author info
source "$HOME/.dotfiles.local";


# Check for git config user.name && git config user.email
if [[ ! $(git config user.name) || ! $(git config user.email) ]]; then
    collect_git_info;
else
  # Print Git author info for confirmation
  printf "\n###  GIT AUTHOR INFO  ###\n"; # Just some dumb formatting
  echo " Name: $(git config user.name)";
  echo "Email: $(git config user.email)";
  printf "\n";

  e_warning "Confirm the Git information above is correct.";

  # Seek confirmation that the Git information above is correct.
  printf "Is this correct? [Y/n] ";
  read GIT_AUTHOR;
  printf "\n";

  if [[ $GIT_AUTHOR =~ ^[Yy]$ || $GIT_AUTHOR == '' ]]; then
    local_git_config  "$(git config user.name)" "$(git config user.email)";
  else
    collect_git_info;
  fi;
fi;


# Source bashrc to make sure the environment is set before moving on
source "$HOME/.bashrc";


# Conditionally install packages
if [[ $NO_PACKAGES ]]; then
  e_header "Skipping package installation...";
else
  # Install Homebrew packages
  source bin/brews;
  # Install Homebrew packages
  source bin/nvm;
  # Install Homebrew packages
  source bin/rvm;

  # Change to bash 4 installed by bin/brews
  if [[ ! $(grep "/usr/local/bin/bash" /etc/shells) ]]; then
    echo /usr/local/bin/bash|sudo tee -a /etc/shells && chsh -s /usr/local/bin/bash;
    e_success "Shell switched to Bash 4";
  else
    e_header "/usr/local/bin/bash already in /etc/shells";
  fi;
fi;


if [[ ! $SERVER ]]; then
  # Ask before potentially overwriting files
  printf "\n";
  e_warning "Warning: This step may modify your OS X system defaults.";
  printf "Continue? [Y/n]";
  read SET_OSX;
  printf "\n";


  # Conditionally set defaults
  if [[ "$SET_OSX" == "n" ]]; then
    e_header "Skipped OS X settings update.";
  else
    source bin/osx;
  fi;
fi;


unset COPY_FILES;


[[ $? ]] && e_success "Restart your shell for changes to take effect";
