#!/bin/bash

# Add tab completion for SSH hostnames based on ~/.ssh/config, ignoring wildcards.
[[ -e "${HOME}/.ssh/config" ]] && complete -o 'default' -o 'nospace' -W "$(grep '^Host' ~/.ssh/config | grep -v "[?*]" | cut -d ' ' -f2 | tr ' ' '\n')" scp sftp ssh;

# Add `killall` tab completion for common apps.
complete -o 'nospace' -W 'Contacts Calendar Dock Finder Mail Safari iTunes SystemUIServer Terminal' killall;

# If possible, add tab completion for many more commands.
# Homebrew's own bash completion script has been linked into /usr/local/share/bash-completion/completions
# bash-completion will automatically source it when you invoke `brew`.

# Any completion scripts in /usr/local/etc/bash_completion.d will continue to be sourced as well.
if [[ $(type -P brew) ]] && [[ -f "$(brew --prefix)/share/bash-completion/bash_completion" ]]; then
  source "$(brew --prefix)/share/bash-completion/bash_completion";

  # Set up completion for aliases
  __git_complete g git;
fi;

# NPM completions.
# @todo This is not compatible with npm workspaces.
source <(npm completion);

# Autocomplete branch names for `gcheck`.
function _gcheck_completion() {
    branches=$(git branch -l | cut -c3-);
    COMPREPLY=($(compgen -W "${branches}" -- "${2}"));
}
complete -F _gcheck_completion gcheck
