#!/bin/bash

# Brew paths
PATH="$(brew --prefix)/bin":"$(brew --prefix)/sbin";

# $HOME/.nvm/versions/node/{version}/bin
PATH="${PATH}:${NVM_BIN}";

# Add RVM to PATH for scripting.
PATH="${PATH}:${HOME}/.rvm/bin";

# Home bin
PATH="${PATH}:${HOME}/.bin";

# Add back default bins.
PATH="${PATH}:/usr/bin:/bin:/usr/sbin:/sbin";

if [ "$(type -P brew)" ]; then
  FINDUTILS="$(brew --prefix findutils)";

  if [[ "${FINDUTILS}" ]]; then
    PATH="${PATH}:${FINDUTILS}/libexec/gnubin";
    MANPATH="${FINDUTILS}/libexec/gnuman:${MANPATH}";
  fi;

  COREUTILS="$(brew --prefix coreutils)";

  if [[ "${COREUTILS}" ]]; then
    PATH="${PATH}:${COREUTILS}/libexec/gnubin";
    MANPATH="${COREUTILS}/libexec/gnuman:${MANPATH}";
  fi;

  GNU_SED="$(brew --prefix gnu-sed)";

  if [[ "${GNU_SED}" ]]; then
    PATH="${PATH}:${GNU_SED}/libexec/gnubin";
    MANPATH="${GNU_SED}/libexec/gnuman:${MANPATH}";
  fi;
else
  # Fall back to macOS default.
  PATH="${PATH}:/libexec/gnubin";
fi;

# Add MySQL.
PATH="${PATH}:/usr/local/mysql/bin";

export PATH;
export MANPATH;
