#!/bin/bash

export INPUTRC="${HOME}/.inputrc";

export NVM_DIR="${HOME}/.nvm"
[ -s "${NVM_DIR}/nvm.sh" ] && \. "${NVM_DIR}/nvm.sh"  # This loads nvm
[ -s "${NVM_DIR}/bash_completion" ] && \. "${NVM_DIR}/bash_completion"  # This loads nvm bash_completion

# Load the shell dotfiles, and then some:
# Shamelessly stolen from @wilto
declare -a FILES=(
  "${HOME}/.prompt" # Custom bash prompt.
  "${HOME}/.bash_config" # Configuration.
  "${HOME}/.aliases" # Aliases.
  "${HOME}/.paths" # Path modifications.
  "${HOME}/.dotfiles.local" # Local and private settings not under version control (e.g. git name/email, package lists).
  "${HOME}/.rvm/scripts/rvm" # Load RVM into a shell session *as a function*.
  "${HOME}/.completions" # Autocompletion scripts.
);

# If these files are readable, source them.
for INDEX in ${!FILES[*]}; do
  [[ -r "${FILES[$INDEX]}" ]] && source "${FILES[$INDEX]}";
done;

unset FILES;

# Source functions files.
for function_file in "${HOME}/.functions/"*; do
  [[ -r "${function_file}" ]] && source "${function_file}";
done;

# Environment variables.
GIT_COMMITTER_NAME="$(git config user.name)";
GIT_COMMITTER_EMAIL="$(git config user.email)";

# Current Node version.
NVM_CURRENT="$(nvm current | sed 's/v//')";

test -d /home/linuxbrew/.linuxbrew && eval $(/home/linuxbrew/.linuxbrew/bin/brew shellenv);
# eval $($(brew --prefix)/bin/brew shellenv)
