#!/bin/bash

export INPUTRC="${HOME}/.inputrc";

# Load the shell dotfiles, and then some:
# Shamelessly stolen from @wilto
declare -a FILES=(
  "${HOME}/.nvm/nvm.sh" # Load NVM.
  "${HOME}/.completions" # Autocompletion scripts.
  "${HOME}/.prompt" # Custom bash prompt.
  "${HOME}/.bash_config" # Configuration.
  "${HOME}/.aliases" # Aliases.
  "${HOME}/.functions" # Functions.
  "${HOME}/.paths" # Path modifications.
  "${HOME}/.dotfiles.local" # Local and private settings not under version control (e.g. git name/email, package lists).
  "${HOME}/.rvm/scripts/rvm" # Load RVM into a shell session *as a function*.
);

# If these files are readable, source them.
for INDEX in ${!FILES[*]}; do
  [[ -r "${FILES[$INDEX]}" ]] && source "${FILES[$INDEX]}";
done;

unset FILES;

export NVM_DIR="${HOME}/.nvm"
[ -s "${NVM_DIR}/nvm.sh" ] && \. "${NVM_DIR}/nvm.sh"  # This loads nvm
[ -s "${NVM_DIR}/bash_completion" ] && \. "${NVM_DIR}/bash_completion"  # This loads nvm bash_completion

# Environment variables.
GIT_COMMITTER_NAME="$(git config user.name)";
GIT_COMMITTER_EMAIL="$(git config user.email)";

# Current Node version.
NVM_CURRENT="$(nvm current | sed 's/v//')";

test -d /home/linuxbrew/.linuxbrew && eval $(/home/linuxbrew/.linuxbrew/bin/brew shellenv);
# eval $($(brew --prefix)/bin/brew shellenv)

# https://stackoverflow.com/a/55993078
export GPG_TTY=$(tty);

# Added after installing gpg.
eval "$(pyenv init --path)";
# Star pyenv.
if command -v pyenv 1>/dev/null 2>&1; then
  eval "$(pyenv init -)";
fi
