#!/bin/bash
# shellcheck disable=SC2034

if [[ "${COLORTERM}" = gnome-* && "${TERM}" = xterm ]] && infocmp gnome-256color >/dev/null 2>&1; then
  export TERM='gnome-256color';
elif infocmp xterm-256color >/dev/null 2>&1; then
  export TERM='xterm-256color';
fi;

# Solarized colors, taken from http://git.io/solarized-colors.
if tput setaf 1 &> /dev/null; then
  tput sgr0; # Reset colors.
  BLACK=$(tput setaf 0);
  BLUE=$(tput setaf 117);
  BOLD=$(tput bold);
  CYAN=$(tput setaf 80);
  DEEP_GREEN=$(tput setaf 112);
  DEEP_RED=$(tput setaf 196);
  GRAY=$(tput setaf 240);
  GREEN=$(tput setaf 150);
  LTGRAY=$(tput setaf 188);
  ORANGE=$(tput setaf 215);
  PURPLE=$(tput setaf 125);
  RED=$(tput setaf 210);
  RESET=$(tput sgr0);
  VIOLET=$(tput setaf 183);
  WHITE=$(tput setaf 15);
  YELLOW=$(tput setaf 222);
else
  BLACK="\e[38;5;0m";
  BLUE="\e[38;5;117m";
  CYAN="\e[38;5;80m";
  DEEP_GREEN="\e[38;5;112m";
  DEEP_RED="\e[38;5;196m";
  GRAY="\e[38;5;240m";
  GREEN="\e[38;5;150m";
  LTGRAY="\e[38;5;188m";
  ORANGE="\e[38;5;215m";
  PURPLE="\e[38;5;125m";
  RED="\e[38;5;210m";
  RESET="\e[0m";
  RESET=$(tput sgr0);
  VIOLET="\e[38;5;183m";
  WHITE="\e[38;5;15m";
  YELLOW="\e[38;5;222m";
fi;

# h/t https://github.com/necolas/dotfiles
prompt_git() {
  local S='';
  local BRANCHNAME='';

  # Check if the current directory is in a Git repository.
  if git rev-parse --is-inside-work-tree &>/dev/null; then

    # check if the current directory is in .git before running git checks.
    if [ "$(git rev-parse --is-inside-git-dir 2> /dev/null)" == 'false' ]; then

      # Ensure the index is up to date.
      git update-index --really-refresh -q &>/dev/null;

      # Check for uncommitted changes in the index.
      if ! git diff --quiet --ignore-submodules --cached; then
        S+="${GREEN}+${GRAY}";
      fi;

      # Check for unstaged changes.
      if ! git diff-files --quiet --ignore-submodules --; then
        S+="${YELLOW}!${GRAY}";
      fi;

      # Check for untracked files.
      if [ -n "$(git ls-files --others --exclude-standard)" ]; then
        S+="${RED}?${GRAY}";
      fi;

      # Check for stashed files.
      if git rev-parse --verify refs/stash &>/dev/null; then
        S+="${PURPLE}\$${GRAY}";
      fi;

    fi;

    # Get the short symbolic ref.
    # If HEAD isn’t a symbolic ref, get the short SHA for the latest commit.
    # Otherwise, just give up.
    BRANCHNAME="$(git symbolic-ref --quiet --short HEAD 2> /dev/null || \
                git rev-parse --short HEAD 2> /dev/null || \
                echo '(unknown)')";

    [ -n "${S}" ] && S=" [${S}]";

    echo -e "${1}${BRANCHNAME}${2}${S}";
  else
    return;
  fi;
}

# Clear prompt variables.
unset PS1;
unset PS2;

# If a the prompt variables aren't set, use the default.
if [[ -z ${PS1} ]]; then
  # Main prompt
  # HH:MM:SS - User@Host
  PS1="\n\[${GRAY}\]\T - \u@\h";
  # New line; Current directory
  PS1+="\n\[${GREEN}\]\$(pwd)";
  # If inside a Git repo, print "on <branch>" at the end of the line.
  PS1+="\$(prompt_git \"\[${GRAY}\] on \[${ORANGE}\]\" \"\[${GRAY}\]\")"; # Git repository details.
  # Prompt on a new line.
  PS1+="\n\[${GREEN}\]\$ \[${LTGRAY}\]";

  # Continuation prompt.
  PS2="\[${GREEN}\]: \[${LTGRAY}\]";
fi;

export PS1;
export PS2;
