#!/bin/bash
#
# Copyright (c) 2024 Ryan Domingue and contributors
# Report bugs at: https://github.com/goodguyry/dotfiles/issues
# This is free software with ABSOLUTELY NO WARRANTY.

# ------------------------------------------------------------------------------
# Prefix commit messages with the Jira ticket ID found in the current branch
# name, if any.
# ------------------------------------------------------------------------------

COMMIT_MSG_FILE=$1
COMMIT_SOURCE=$2
SHA1=$3

changes=$(git diff-index --cached --exit-code HEAD);
changes_length=${#changes};

# Do nothing if the commit is empty, we're amending a commit, or this is a merge commit.
if [[ $changes_length == 0 || 'merge' == "$COMMIT_SOURCE" || $SHA1 ]]; then
  exit
fi

if [ -z "$BRANCHES_TO_SKIP" ]; then
  BRANCHES_TO_SKIP=(master main develop test production preprod staging qa);
fi;

BRANCH_NAME=$(git symbolic-ref --short HEAD);
BRANCH_NAME=$(echo "${BRANCH_NAME}" | tr '[:lower:]' '[:upper:]');

BRANCH_EXCLUDED=$(printf "%s\n" "${BRANCHES_TO_SKIP[@]}" | grep -c "^$BRANCH_NAME$");

if [[ "${BRANCH_NAME}" =~ ([A-Z0-9]+-[0-9]+) ]]; then
  # Verify branch name
  if ! [[ $BRANCH_EXCLUDED -eq 1 ]] && ! [[ $BRANCH_IN_COMMIT -ge 1 ]]; then
    sed -i.bak -e "1s/^/${BASH_REMATCH[1]} /" "${COMMIT_MSG_FILE}";
  fi;
fi;
