#!/bin/bash
# Creates the .extras file with Git credentials started
# You can use this to add a few custom commands without the need to fork this entire repository
# or to add commands you donÕt want to commit to a public repository.

function create_extras() {
  EXTRAS_FILE="$HOME/.extras"
  touch "$EXTRAS_FILE"
  
  printf "# Git credentials\n\n" > "$EXTRAS_FILE"
  
  printf "# Add your name below\n" >> "$EXTRAS_FILE"
  printf "GIT_AUTHOR_NAME=\"\"\n\n" >> "$EXTRAS_FILE"
  
  printf "# Add your email below\n" >> "$EXTRAS_FILE"
  printf "GIT_AUTHOR_EMAIL=\"\"\n\n" >> "$EXTRAS_FILE"
  
  printf "GIT_COMMITTER_NAME=\"\$GIT_AUTHOR_NAME\"\n" >> "$EXTRAS_FILE"
  printf "GIT_COMMITTER_EMAIL=\"\$GIT_AUTHOR_EMAIL\"\n\n" >> "$EXTRAS_FILE"
  
  printf "# Set the credentials (modifies ~/.gitconfig)\n" >> "$EXTRAS_FILE"
  printf "git config --global user.name \"\$GIT_AUTHOR_NAME\"\n" >> "$EXTRAS_FILE"
  printf "git config --global user.email \"\$GIT_AUTHOR_EMAIL\"\n" >> "$EXTRAS_FILE"
}
