#!/bin/bash


# ***
# Help text
# ***
function run_help() {

cat <<EOT

Dotfiles - Ryan Domingue - http://ryandomingue.com/

Usage: $(basename "$0") [options]

Options:
    -h, --help            Print this help text
    -c, --copy            Copy the files in place instead of linking
    -n, --no-packages     Suppress package installations and updates (including casks)
    -s, --server          Skip OS X-related packages/settings

 Notes:

 1. `gitconfig` is always copied, regardless of the option passed.
 2. `--copy` and `--server` also suppress initializing a Git repo and pulling updates from Github

Documentation can be found at https://github.com/goodguyry/dotfiles

Copyright (c) Ryan Domingue
Licensed under the MIT license.
EOT

}


# Create a directory if it doesn't already exist
function mkdirs() {
  if [[ ! -d $@ ]]; then
    mkdir $@;
    echo "Created $@";
  fi;
}
