#!/bin/bash
# shellcheck disable=SC1091
#
# Copyright (c) 2024 Ryan Domingue and contributors
# Report bugs at: https://github.com/goodguyry/dotfiles/issues
# This is free software with ABSOLUTELY NO WARRANTY.

# ------------------------------------------------------------------------------
# usage: installbrews [--cask] <list>
#
# Install a list of brew packages if they're not already installed.
# ------------------------------------------------------------------------------

source "${DOTFILES_ROOT}/lib/status";

function installbrews() {
  test "$1" = --cask && { cask=$1; shift; }

  for brew in "${@}"; do
    if brew list "${brew}" &> /dev/null; then
      status --info "${brew} is already installed.";
    else
      brew install "${brew}" "${cask}";
    fi;
  done;

  if [[ $? ]]; then
    status --success 'Brew packages are ready.';
  else
    status --error 'There was a problem installing Brew packages.';
  fi
}
