#!/bin/bash
#
# Copyright (c) 2024 Ryan Domingue and contributors
# Report bugs at: https://github.com/goodguyry/dotfiles/issues
#
# This is free software with ABSOLUTELY NO WARRANTY.
#
# Create a directory if it doesn't already exist.
function mkdirs() {
  for dir in $(realpath "${@}"); do
    if [[ ! -d "${dir}" ]]; then
      mkdir -pv "${dir}";
    fi;
  done
}
