#!/bin/bash
#
# Copyright (c) 2024 Ryan Domingue and contributors
# Report bugs at: https://github.com/goodguyry/dotfiles/issues
# This is free software with ABSOLUTELY NO WARRANTY.

# ------------------------------------------------------------------------------
# usage: setfile <target> <link-name>
# @todo Support a -c flag for copyings w/ rsync.
#
# Symlink a file, forcing a replacement if necessary.
# ------------------------------------------------------------------------------

function setfile() {
  local target;
  local link_name="${2}";

  # if $copy
  # rsync -avz --quiet "${target}" "${link_name}";
  # else

  target=$(realpath "${1}");

  ln -fs "${target}" "${link_name}";
}
