#!/bin/bash
#
# Copyright (c) 2024 Ryan Domingue and contributors
# Report bugs at: https://github.com/goodguyry/dotfiles/issues
# This is free software with ABSOLUTELY NO WARRANTY.

# usage: status <message>
#    or: status --info <message>
#    or: status --success <message>
#    or: status --error <message>
#    or: status --warning <message>
#
# Prints a color- and emoji-coded status message.

function status() {
  local deep_green=$(tput setaf 112);
  local deep_red=$(tput setaf 196);
  local ltgray=$(tput setaf 188);
  local yellow=$(tput setaf 222);
  local reset=$(tput sgr0);

  local prompt="$(basename ${0})";
  if [[ "${prompt}" =~ install|run ]]; then
    # Strip `dotfiles` from subcommands, mostly to shorten the prompt.
    prompt=$(echo "${prompt}" | sed 's/dotfiles-//g');
  fi

  local prefix="${ltgray}=>";
  local goodbye=false;

  case "$1" in
    --info)
      prefix="${ltgray}💡";
      shift;
      ;;
    --success)
      prefix="${deep_green}✅";
      shift;
      ;;
    --error)
      prefix="${deep_red}❌";
      goodbye=true;
      shift;
      ;;
    --warning)
      prefix="${yellow}⚠️ ";
      shift;
      ;;
  esac

  local msg="$1";

  printf "${prefix} ${prompt}: %s${reset}\n" "${msg}";

  if $goodbye; then
    printf "${prefix} ${prompt}: Exiting...${reset}\n";
    exit 1;
  fi
}
