#!/bin/bash

##
# Install Mac App Store purchases.
##

# Source utils.
DOTFILES_DIRECTORY="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && cd .. && pwd )";
source "${DOTFILES_DIRECTORY}/utils/logger.sh";
source "${DOTFILES_DIRECTORY}/utils/brew-check.sh";

# Check for `mas`.
if [[ ! "$(type -P mas)" ]]; then
  brew install mas;
fi;

# Capture account.
ACCOUNT=$(mas account);

# Sign in if not signed in.
if [[ "${ACCOUNT}" == *"Not signed in"* ]]; then
  # Ask for Apple ID.
  printf '\n';
  log_warning 'You are not signed in to the App Store';
  printf 'Enter your App Store Apple ID ';
  read APPLE_ID;
  printf '\n';

  # Check APPLE_ID value.
  if [[ "$(echo -e ${APPLE_ID} | tr -d '[:space:]')" != '' ]]; then
    if [[ $(mas signin "${APPLE_ID}") && $? -eq 0 ]]; then
      log_header "You are signed in with ${APPLE_ID}";
    else
      log_error "Something bad happened...";
      exit;
    fi;
  else
    exit;
  fi;
else
  log_header "You are signed in with ${ACCOUNT}";
fi;

# Install apps.

# 2Do
mas install 477670270;
# Bear
mas install 1091189122;
# Better Rename 9
mas install 414209656;
# Byword
mas install 420212497;
# Duo
mas install 777886035;
# Frank DeLoupe
mas install 530458789;
# GIPHY Capture
mas install 668208984;
# Pixelmator
mas install 407963104;
# Reeder
mas install 880001334;
# Slack
mas install 803453959;
# SnippetsLab
mas install 1006087419;
# The Unarchiver
mas install 425424353;
# Things
mas install 904280696;
# Tweetbot
mas install 557168941;
