#!/bin/bash

# Install Homebrew and Homebrew packages, native applications, and fonts.


# Source utils.
DOTFILES_DIRECTORY="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && cd .. && pwd )";
source "${DOTFILES_DIRECTORY}/utils/logger.sh";
source "${DOTFILES_DIRECTORY}/utils/brew-check.sh";


# Check for existing brew before installing.
function brew_install() {
  if $(brew list ${1} &> /dev/null); then
    log_warning "${1} already installed";
  else
    brew install ${@};
  fi;
}

# Check for an existing cask or app file before installing.
function brew_cask_install() {
  APP=$(brew cask info ${1} | grep \\.app | sed -e 's/\ (App)//');
  if $(brew cask list ${1} &> /dev/null) || $(ls /Applications/ | grep -i "${APP}" &> /dev/null); then
    log_warning "${1} already installed";
  else
    brew cask install ${@};
  fi;
}

# CLI packages

log_header 'Installing CLI packages...';

# GNU File, Shell, and Text utilities.
brew_install coreutils;

# Install GNU `find`, `locate`, `updatedb`, `xargs` and `sed`, g-prefixed.
brew_install findutils --with-default-names;
brew_install gnu-sed --with-default-names;

# Install wget with IRI support.
brew_install wget --enable-iri;

# Install more recent versions of some macOS tools.
brew_install grep;
brew_install openssh;
brew_install rsync;

# Install latest Vim.
brew_install vim --with-override-system-vi;

# Install Bash 4.
brew_install bash;
brew_install bash-completion2;

# Install font tools.
brew tap bramstein/webfonttools;
brew_install sfnt2woff;
brew_install sfnt2woff-zopfli;
brew_install woff2;

# Install other useful binaries.
brew_install gist;
brew_install libdvdcss;
brew_install mas;
brew_install moreutils;
brew_install mysql;
brew_install packer;
brew_install phantomjs;
brew_install pigz;
brew_install tree;

brew cleanup;

[[ $? ]] && log_success 'Homebrew packages installed.';

# Native Apps

log_header 'Installing casks (native apps)...';

# Tap brew-cask.
brew tap caskroom/cask;
brew tap caskroom/versions;

# Install native applications.
brew_cask_install 1Password;
brew_cask_install alfred;
brew_cask_install appcleaner;
brew_cask_install atext;
brew_cask_install betterzip;
brew_cask_install caffeine;
brew_cask_install chronosync;
brew_cask_install clamxav;
brew_cask_install clipy;
brew_cask_install coconutbattery;
brew_cask_install dropbox;
brew_cask_install firefox;
brew_cask_install firefoxdeveloperedition;
brew_cask_install gitify;
brew_cask_install google-chrome-canary;
brew_cask_install google-chrome;
brew_cask_install handbrake;
brew_cask_install imageoptim;
brew_cask_install macdown;
brew_cask_install onyx;
brew_cask_install opera-beta;
brew_cask_install opera-developer;
brew_cask_install opera-mobile-emulator;
brew_cask_install opera;
brew_cask_install rar;
brew_cask_install safari-technology-preview;
brew_cask_install sequel-pro;
brew_cask_install sketch;
brew_cask_install sublime-text;
brew_cask_install suspicious-package;
brew_cask_install torbrowser;
brew_cask_install transmission;
brew_cask_install transmit;
brew_cask_install vagrant;
brew_cask_install virtualbox;
brew_cask_install visual-studio-code;
brew_cask_install vlc;

# System Preferences panes
brew_cask_install web-sharing;

# QuickLook Plugins
brew_cask_install qlcolorcode;
brew_cask_install qlimagesize;
brew_cask_install qlmarkdown;
brew_cask_install qlstephen;
brew_cask_install quicklook-csv;
brew_cask_install webpquicklook;

brew cask cleanup;

[[ $? ]] && log_success 'Homebrew Casks installed';

# Fonts

log_header 'Installing fonts...';

# Tap brew-cask fonts
brew tap caskroom/fonts;

# Install fonts.
brew_cask_install font-hack;
brew_cask_install font-inconsolata;
brew_cask_install font-lato;
brew_cask_install font-merriweather-sans;
brew_cask_install font-merriweather;
brew_cask_install font-nunito;
brew_cask_install font-open-sans-condensed;
brew_cask_install font-open-sans-hebrew-condensed;
brew_cask_install font-open-sans-hebrew;
brew_cask_install font-open-sans;
brew_cask_install font-pt-mono;
brew_cask_install font-pt-sans;
brew_cask_install font-pt-serif;
brew_cask_install font-roboto-condensed;
brew_cask_install font-roboto-mono;
brew_cask_install font-roboto-slab;
brew_cask_install font-source-code-pro;
brew_cask_install font-source-sans-pro;
brew_cask_install font-source-serif-pro;

[[ $? ]] && log_success 'Fonts installed';
