#!/bin/bash
#
# Check for, install and update Homebrew and Homebrew packages,
#   including native applications with Homebrew Cask


# Source utils
DOTFILES_DIRECTORY="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && cd .. && pwd )";
source "${DOTFILES_DIRECTORY}/utils/logger.sh";
source "${DOTFILES_DIRECTORY}/utils/brew-check.sh";

log_header 'Installing new formulae...';


# Install CLI packages

# GNU File, Shell, and Text utilities
brew install coreutils;

# Install GNU `find`, `locate`, `updatedb`, and `xargs`, g-prefixed
brew install findutils --with-default-names;

# Install wget with IRI support
brew install wget --enable-iri;

# Install more recent versions of some OS X tools
brew install gnu-sed --with-default-names;
brew install grep;
brew install openssh;
brew install vim --with-override-system-vi;

# Install Bash 4
brew install bash;
brew install bash-completion2;

# Install font tools.
# https://github.com/bramstein/homebrew-webfonttools
brew tap bramstein/webfonttools;
brew install sfnt2woff;
brew install sfnt2woff-zopfli;
brew install woff2;

# Install other useful binaries
brew install gist;
brew install libdvdcss;
brew install mas;
brew install moreutils;
brew install mysql;
brew install packer;
brew install phantomjs;
brew install pigz;
brew install rar;
brew install tree;

brew cleanup;

[[ $? ]] && log_success 'Homebrew packages installed.';


# Install native applications
log_header 'Installing casks (native apps)...';

# Install brew-cask
brew tap caskroom/cask;
brew tap caskroom/versions;

# Link Homebrew casks in `/Applications` rather than `~/Applications`
export HOMEBREW_CASK_OPTS='--appdir=/Applications';

# Native apps
brew cask install 1Password;
brew cask install alfred;
brew cask install atext;
brew cask install caffeine;
brew cask install chronosync;
brew cask install clamxav;
brew cask install clipy;
brew cask install coconutbattery;
brew cask install dropbox;
brew cask install firefox;
brew cask install firefoxdeveloperedition;
brew cask install gitify;
brew cask install google-chrome-canary;
brew cask install google-chrome;
brew cask install handbrake;
brew cask install imageoptim;
brew cask install macdown;
brew cask install nvalt;
brew cask install onyx;
brew cask install opera-beta;
brew cask install opera-developer;
brew cask install opera-mobile-emulator;
brew cask install opera;
brew cask install safari-technology-preview;
brew cask install sequel-pro;
brew cask install sketch;
brew cask install sublime-text;
brew cask install suspicious-package;
brew cask install torbrowser;
brew cask install transmission;
brew cask install transmit;
brew cask install vagrant;
brew cask install virtualbox;
brew cask install visual-studio-code;
brew cask install vlc;
brew cask install webkit-nightly;

# System Preferences panes
brew cask install web-sharing;

# QuickLook Plugins
brew cask install betterzipql;
brew cask install qlcolorcode;
brew cask install qlimagesize;
brew cask install qlmarkdown;
brew cask install qlstephen;
brew cask install quicklook-csv;
brew cask install webpquicklook;

brew cask cleanup;


[[ $? ]] && log_success 'Homebrew Casks installed';
