#!/bin/bash
# Install Ruby via NVM; install Gems
# https://rvm.io/


# Source utils
DOTFILES_DIRECTORY="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && cd .. && pwd )";
source "${DOTFILES_DIRECTORY}/utils/logger.sh";


# Install RVM
if [ ! "$(type -P rvm)" ]; then
  log_header 'Installing RVM...';
  curl -L https://get.rvm.io | bash -s stable --ignore-dotfiles --autolibs=enable;
fi;


# Check for the RVM install location
RVM_LOC=${rvm_path:="$HOME/.rvm"};
# Source rvm
source "${RVM_LOC}/scripts/rvm";


# Install Ruby 2.3.0
rvm install ruby-2.3.0;
rvm use 2.3.0 --default;

# Update PATH before installing Gems so they end up where intended
export PATH=${GEM_HOME}/bin:${GEM_HOME}@global/bin:${MY_RUBY_HOME}/bin:${PATH};

rvm cleanup all;


# Install Gems
log_header 'Installing Gems...';
GEM_LIST='jekyll octopress-autoprefixer rouge sass';
gem install ${GEM_LIST} --no-document;

gem cleanup;


[[ $? ]] && log_success 'Gems installed.';
