#!/bin/bash

##
# Install RVM, Ruby, and Gems.
##

# Source utils.
DOTFILES_DIRECTORY="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && cd .. && pwd )";
source "${DOTFILES_DIRECTORY}/utils/logger.sh";

# Set Ruby version.
RUBY_VERSION='2.3.1';

# Install RVM.
if [ ! "$(type -P rvm)" ]; then
  log_header 'Installing RVM...';
  curl -L https://get.rvm.io | bash -s stable --ignore-dotfiles --autolibs=enable;
fi;

# Source rvm.
RVM_LOC=${rvm_path:="$HOME/.rvm"};
source "${RVM_LOC}/scripts/rvm";

# Install Ruby.
rvm install "ruby-${RUBY_VERSION}";
rvm use "${RUBY_VERSION}" --default;

# Update PATH before installing Gems so they end up where intended.
export PATH=${GEM_HOME}/bin:${GEM_HOME}@global/bin:${MY_RUBY_HOME}/bin:${PATH};

rvm cleanup all;

# Install Gems.
log_header 'Installing Gems...';

GEM_LIST='jekyll octopress-autoprefixer rouge sass';
gem install ${GEM_LIST} --no-document;

gem cleanup;

# Install Vagrant plugins
vagrant plugin install vagrant-ghost;

# Add Dreambox
vagrant box add goodguyry/dreambox --provider virtualbox;

[[ $? ]] && log_success 'Gems installed.';
