#!/bin/bash
# Installs Sublime Text packages and settings


# Source utils
DOTFILES_DIRECTORY="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && cd .. && pwd )";
source "${DOTFILES_DIRECTORY}/utils/logger.sh";


# Set Sublime Text settings directory
SUBLIME_PACKAGES="${HOME}/Library/Application Support/Sublime Text 3/Packages";

# Create the directory path if it doesn't exist
[[ ! -d "${SUBLIME_PACKAGES}/User" ]] && mkdir -p "${SUBLIME_PACKAGES}/User";


# Clone a Sublime Text 3 package repo to Packages directory
function add_sublime_package() {
  local REPO="${1}"
  local PACKAGE="${2}";
  if [[ ! -d "${SUBLIME_PACKAGES}/${PACKAGE}" ]]; then
    log_header "Cloning ${PACKAGE}";
    git clone "https://github.com/${REPO}" "${SUBLIME_PACKAGES}/${PACKAGE}"  &> /dev/null;
    [[ $? ]] && log_success "${PACKAGE} installed."
  else
    log_header "${PACKAGE} already exists...";
  fi;
}


# Clone packages
log_header 'Adding Sublime Text packages...';

add_sublime_package 'daylerees/colour-schemes.git'                   'ColourSchemes';
add_sublime_package 'y0ssar1an/CSS3.git'                             'CSS3';
add_sublime_package 'spadgos/sublime-jsdocs.git'                     'DocBlockr';
add_sublime_package 'sindresorhus/editorconfig-sublime.git'          'EditorConfig';
add_sublime_package 'colinta/SublimeFileDiffs.git'                   'FileDiffs';
add_sublime_package 'kemayo/sublime-text-git.git'                    'Git';
add_sublime_package 'jisaacks/GitGutter.git'                         'GitGutter';
add_sublime_package 'siteleaf/liquid-syntax-mode.git'                'LiquidSyntax';
add_sublime_package 'braver/MarkdownHighlighting.git'                'MarkdownHighlighting';
add_sublime_package 'titoBouzout/SideBarEnhancements.git'            'SideBarEnhancements';
add_sublime_package 'lamotta/specialsboard.git'                      'SpecialsBoard';
add_sublime_package 'P233/Syntax-highlighting-for-Sass.git'          'SyntaxHighlightingForSass';
add_sublime_package 'pichillilorenzo/JavaScript-Completions.git'     'JavaScriptCompletions';
add_sublime_package 'bgreenlee/sublime-github.git'                   'Github';
add_sublime_package 'SublimeLinter/SublimeLinter3.git'               'SublimeLinter';
add_sublime_package 'roadhump/SublimeLinter-eslint.git'              'SublimeLinter-eslint';

log_success 'Sublime Text packages installed.'
log_warning 'Install Package Control: https://packagecontrol.io/installation'
log_warning 'Install Markdown Preview with Package Control'


# Sublime Text settings
set_file \
  'sublime/Default (OSX).sublime-keymap' \
  "${SUBLIME_PACKAGES}/User/Default (OSX).sublime-keymap";

set_file \
  'sublime/Markdown.sublime-settings' \
  "${SUBLIME_PACKAGES}/User/Markdown.sublime-settings";

set_file \
  'sublime/Preferences.sublime-settings' \
  "${SUBLIME_PACKAGES}/User/Preferences.sublime-settings";

set_file \
  'sublime/Ruby.sublime-settings' \
  "${SUBLIME_PACKAGES}/User/Ruby.sublime-settings";

set_file \
  'sublime/Shell-Unix-Generic.sublime-settings' \
  "$SUBLIME_PACKAGES/User/Shell-Unix-Generic.sublime-settings";

set_file \
  'sublime/Git.sublime-settings' \
  "$SUBLIME_PACKAGES/User/Git.sublime-settings";


[[ $? ]] && log_success 'Sublime settings done.'
