#!/bin/bash

# ----------------------------------------------
# Renames all files with an appended number; directories are skipped by default
#
#   Usage: rn string [-[1-999]] [1-999] [-d] [-a] [.ext]
#
#   string : A string representing the new filename
#
#       -n : (optional) A number, with a preceding dash, representing the total
#            number of digit places for the count. Default is 2 (01) unless reset
#            Example: -5 -> 00001
#
#        n : (optional) A number representing the starting point for the count
#
#       -d : (optional) Flag to rename only directories
#
#       -a : (optional) Flag to rename both files and directories
#
#     .ext : (optional) File extension (including the .) of the file type to rename
#
#   TODO:
#     Remove item's number on rename
#     Count folders and files separately
#     Remove strict argument order (name being first)
#     Check if file already exists; increment counter if so
#     Or maybe just get rid of this hulking mess altogether...
# ----------------------------------------------

function rn() {

  if [[ $1 == "-h" || $1 == "--help" ]]; then rn_help; return; fi

  if [ $# -lt 1 ]; then echo "Error: New filename required."; return; fi

  x=1
  renameAllItems=false
  renameDirectoriesOnly=false
  renameSpecificExtension=false

  for arg in "$@"; do

    newName="${1}"

    currentArg="${@:x:1}"

    regFlagAlpha="\-[a|d|0-999]"
    regNum="[0-999]"
    regExt="\.[a-z|0-9]"

    if [[ "$currentArg" =~ $regFlagAlpha ]]; then
      flag=$(echo ${arg} | cut -d '-' -f 2)

      if [[ "$flag" == "a" ]]; then
        renameAllItems=true
      elif [[ "$flag" == "d" ]]; then
        renameDirectoriesOnly=true
      else
        zeroPadding=$flag; fi

      if ($renameAllItems) && ($renameDirectoriesOnly); then
        echo "Error: Cannot flag \"All files\" and \"Directories only\" together"
        unset renameAllItems
        unset renameDirectoriesOnly
        return
      fi

    elif [[ "$currentArg" =~ $regExt ]]; then
      fileExtension=$(echo ${arg} | cut -d '.' -f 2)
      renameSpecificExtension=true

    elif [[ "$currentArg" =~ $regNum ]]; then
      startingPoint=$arg
    fi

    x=$((x+1))

  done

  #default startingPoint and zeroPadding if all else fails
  if [[ -z $startingPoint ]]; then startingPoint=1; fi
  if [[ -z $zeroPadding ]]; then zeroPadding=2; fi

  fileCount=$(ls -1 | wc -l)

  # increase the base digits places for large numbers
  if [[ $(( $fileCount + $startingPoint )) -gt 999 ]]; then
    zeroPadding=4
  elif [[ $(( $fileCount + $startingPoint )) -gt 99 ]]; then
    zeroPadding=3
  fi

  # function to rename files
  renameFile() {
    fileName="${1%.*}"
    ext="${1##*.}"
    if $renameSpecificExtension ; then
      if [[ "$fileExtension" == "${ext}" ]]; then
        mv "$i" "${newName}_${2}.${ext}"
      else
        return
      fi
    else
      mv "$i" "${newName}_${2}.${ext}"
    fi
  }

  # function to rename folders
  renameDirectory() {
    folderName="$1"
    mv "$i" "${newName}_${2}"
  }

  for i in *; do
    n=$(printf "%0*d" $zeroPadding $startingPoint)

    if $renameAllItems ; then
      if [[ -d "$i" ]]; then
        renameDirectory $i $n
      elif [[ -f "$i" ]]; then
        renameFile $i $n
      fi
    fi

    if $renameDirectoriesOnly ; then
      if [[ -d "$i" ]]; then
        renameDirectory $i $n
      fi
    fi

    if ! $renameAllItems && ! $renameDirectoriesOnly ; then
      if [[ -f "$i" ]]; then
        renameFile $i $n
      fi
    fi

    startingPoint=$(($startingPoint+1))
  done

  # cleanup
  unset zeroPadding
  unset startingPoint
  unset currentArg
  unset renameAllItems
  unset renameDirectoriesOnly
  unset renameSpecificExtension
  unset fileExtension
  unset flag
}

function rn_help() {

cat <<EOT

Renames all files with an appended number; directories are skipped by default

Usage: rn string [-[1-999]] [1-999] [-d] [-a] [.ext]

  string : A string representing the new filename

      -n : (optional) A number, with a preceding dash, representing the total
           number of digit places for the count. Default is 2 (01) unless reset
           Example: -5 -> 00001

       n : (optional) A number representing the starting point for the count

      -d : (optional) Flag to rename only directories

      -a : (optional) Flag to rename both files and directories

    .ext : (optional) File extension (including the .) of the file type to rename

EOT

}