#!/bin/bash

# Change working directory to the top-most Finder window location
# http://helpx.adobe.com/photoshop/kb/unit-type-conversion-error-applescript.html
function cdf() { # short for `cdfinder`
  cd "$(osascript -e 'tell app "Finder" to POSIX path of (insertion location as alias)')";
}
