#!/bin/bash

# git branch ahead/behind another
function gcheck() {
  # use first argument or master
  original=${1-master};

  # use the second argument or current branch if not given
  current=`git branch | grep \* | sed s/\*\ //`;
  compare=${2-$current};

  # run git rev-list and capture numbers returned
  result=`git rev-list --left-right --count $original...$compare`;

  numbers=($result);
  printf "\n";
  # print numbers in a pretty message
  if [ ${numbers[0]} -gt 0 ]; then
    echo -e "$(tput setaf 136)$compare is ${numbers[0]} commits behind $original$(tput sgr0)";
  fi;
  if [ ${numbers[1]} -gt 0 ]; then
    echo -e "$(tput setaf 64)$compare is ${numbers[1]} commits ahead of $original$(tput sgr0)";
  fi;
}
