#!/bin/bash

# **
# Switch to projects folder; open it in Sublime Text
#   Usage: p [project-name] [subdirectory]
# **
function p() {
  # Check for passed argument(s)
  if [ $# -gt 0 ]; then
    # Change to the project root
    cd "$HOME/Projects/$1";

    # Check for Sublime Text
    if [[ $(type -P subl) ]]; then
      # Check for a passed subdirectory
      if [[ $# -gt 1 ]]; then
        # Open the passed subdirectory in Sublime Text
        subl $2;
      else
        # Open the project root in Sublime Text
        subl .;
      fi;
    fi;

    # Check for a .git repo
    if $(git rev-parse --is-inside-work-tree &> /dev/null); then
      clear;
      git status;
      # Bring Terminal forward
      osascript -e 'tell app "Terminal" to activate';
    fi;
  else
    # No arguments; change to $HOME/Projects
    cd "$HOME/Projects";
  fi;
}
