#!/bin/bash

# ----------------------------------------------
# Add a timestamp to a file or folder
#
#   Usage: ts [-d] string
#
#     -d (optional) : duplicate item before appending the timestamp
#     -s=SEPARATOR (optional) : set the separator between the item name and the timestamp
#
#   Change date format in $stamp to alter output
# ----------------------------------------------

function ts() {
  ERRORMSG="Error: A file or folder is required for timestamping";
  STAMP=$(date +%Y%m%d_%H%M%S);
  DUP=false;
  SEP="_"; # Default separator

  # No args were given
  if [ $# -lt 1 ]; then
    echo "$ERRORMSG";
    return;
  fi;

  # Test for flags
  for opt in $@; do
    case $opt in
      -d) DUP=true ;;   # Duplicate the item before appending the timestamp
      -s*) SEP="${opt##*-s=}" ;; # Set the separator between the itme name and the timestamp
      *) ITEM=$opt ;;   # Set ITEM to the other argument
    esac
  done;

  # Make sure ITEM is set before proceeding
  if [ -z "$ITEM" ]; then
    echo "$ERRORMSG";
    return;
  fi;

  if [ -d "$ITEM" ]; then
    # Split off the trailing slash (if it's there)
    NAME="${ITEM%/*}";
    # Clear the extension
    EXT="";
  else
    # Split the name from the extension
    NAME="${ITEM%.*}";
    # Include the dot in the extension to make things easier in the next step
    EXT=".${ITEM##*.}";
  fi

  if [ $DUP == true ]; then
    # Duplicate the item with timestamp
    cp -r "$NAME"{,"$SEP$STAMP"}"$EXT";
  else
    # Timestamp the item without duplication
    mv "$NAME"{,"$SEP$STAMP"}"$EXT";
  fi;

  unset SEP;
}
