#!/bin/bash

# Create a temporary plain text file
# Usage: `tmp ext` (creates file: temp.[date string].ext)
# If no extension is passed, defaults to "md"
function tmp() {
  prefix="temp";
  suffix=$(date +%Y%m%d%H%M%S);
  ext="${1:-md}";
  filename="$prefix.$suffix.$ext";
  touch $filename;
}
