#!/bin/bash

# Load the shell dotfiles, and then some:
# Shamelessly stolen from @wilto
declare -a files=(
    $HOME/.rvm/scripts/rvm # Load RVM into a shell session *as a function*
    $HOME/.bash_config # Configuration
    $HOME/.aliases # Aliases
    $HOME/.bash_functions/* # Functions
    $HOME/.bash_prompt # Custom bash prompt
    $HOME/.extras # Local and private settings not under version control (e.g. git credentials)
    $HOME/.bash_paths # Path modifications
    $HOME/.nvm/nvm.sh # Load NVM
)

# If these files are readable, source them
for index in ${!files[*]}
do
    if [[ -r ${files[$index]} ]]; then
        source ${files[$index]}
    fi
done

unset files

## Use the installed stable version of Node
nvm use stable > /dev/null

# If possible, add tab completion for many more commands
[ -f /etc/bash_completion ] && source /etc/bash_completion
