#!/bin/bash

# Personal environment variables, startup programs, aliases and functions.

# Personal aliases and functions should go in ~/.bashrc.
# If you're scared, put 'em there. I do what I want.
# System wide environment variables and startup programs are in /etc/profile.
# System wide aliases and functions are in /etc/bashrc.

# Load the shell dotfiles, and then some:
# Shamelessly stolen from @wilto
declare -a files=(
    $HOME/.rvm/scripts/rvm # Load RVM into a shell session *as a function*
    $HOME/.bash_config # Configuration
    $HOME/.aliases # Aliases
    $HOME/.functions/* # Functions
    $HOME/.bash_prompt # Custom bash prompt
    $HOME/.extras # Local and private settings not under version control (e.g. git credentials)
    $HOME/.bash_paths # Path modifications
)

# If these files are readable, source them
for index in ${!files[*]}
do
    if [[ -r ${files[$index]} ]]; then
        source ${files[$index]}
    fi
done

unset files


# If possible, add tab completion for many more commands
[ -f /etc/bash_completion ] && source /etc/bash_completion
