#!/bin/bash

# extend `$PATH`
PATH="/usr/local/bin:$PATH";
PATH="$PATH:/usr/local/sbin";
PATH="$PATH:/usr/bin";
PATH="$PATH:$HOME/usr/local/bin";
PATH="$PATH:$HOME/.bin";
PATH="$PATH:$HOME/bin";
# Add RVM to PATH for scripting
PATH="$PATH:$HOME/.rvm/bin";
# Add brew-installed GNU core utilities bin
if [ $(type -P brew) ]; then
  PATH="$PATH:$(brew --prefix coreutils)/libexec/gnubin";
fi;
# Add MySQL
PATH="$PATH:/usr/local/mysql/bin";

export PATH;
