#!/bin/bash

# @gf3’s Sexy Bash Prompt, inspired by “Extravagant Zsh Prompt”
# Shamelessly copied from https://github.com/gf3/dotfiles
# Screenshot: http://i.imgur.com/s0Blh.png

if [[ $COLORTERM = gnome-* && $TERM = xterm ]] && infocmp gnome-256color >/dev/null 2>&1; then
  export TERM=gnome-256color
elif infocmp xterm-256color >/dev/null 2>&1; then
  export TERM=xterm-256color
fi

BLACK="\033[30m"
RED="\033[31m"
GREEN="\e[38;5;86m"
YELLOW="\033[33m"
BLUE="\e[38;5;25m"
PURPLE="\033[35m"
CYAN="\033[36m"
WHITE="\e[38;5;15m"
RESET="\e[38;5;249m"
GRAY="\e[38;5;240m"
LTGRAY="\e[38;5;246m"
ORANGE="\e[38;5;208m"

export BLACK
export RED
export GREEN
export YELLOW
export BLUE
export PURPLE
export CYAN
export WHITE
export RESET
export GRAY

function parse_git_dirty() {
  [[ $(git status 2> /dev/null | tail -n1) != *"working directory clean"* ]] && echo " ∆"
}

function parse_git_branch() {
  git branch --no-color 2> /dev/null | sed -e '/^[^*]/d' -e "s/* \(.*\)/\1$(parse_git_dirty)/"
}

export PS1="\n\[$GRAY\]\T - \u@\h\n\[$BLUE\]\$PWD\[$GRAY\]\$([[ -n \$(git branch 2> /dev/null) ]] && echo \" on \")\[$ORANGE\]\$(parse_git_branch)\[$BLUE\]\n\$ \[$RESET\]"
export PS2="\[$BLUE\]: \[$RESET\]"
