#!/bin/bash

# extend `$PATH`
export PATH="/usr/local/bin:$PATH"
export PATH="$PATH:/usr/bin"
export PATH="$PATH:$HOME/.bin"
export PATH="$PATH:$HOME/bin"
# Add RVM to PATH for scripting
export PATH="$PATH:$HOME/.rvm/bin"
# Add brew-installed GNU core utilities bin
export PATH="$PATH:$(brew --prefix coreutils)/libexec/gnubin"