#!/bin/bash

# Make vim the default editor
export EDITOR="vim"

# Don't clear the screen after quitting a manual page
export MANPAGER="less -X"

# Larger bash history (allow 32³ entries; default is 500)
export HISTSIZE=32768
export HISTFILESIZE=$HISTSIZE
export HISTCONTROL=ignoredups

# Make some commands not show up in history
export HISTIGNORE="cd*:cd -:pwd;exit:date:* --help:ssh *"

# timestamps for bash history. www.debian-administration.org/users/rossen/weblog/1
HISTTIMEFORMAT='%F %T '
export HISTTIMEFORMAT

# Prefer US English and use UTF-8
export LANG="en_US"
export LC_ALL="en_US.UTF-8"

# Link Homebrew casks in `/Applications` rather than `~/Applications`
export HOMEBREW_CASK_OPTS="--appdir=/Applications"

# Add `killall` tab completion for common apps
complete -o "nospace" -W "Contacts Calendar Dock Finder Mail Safari iTunes SystemUIServer Terminal" killall

# Add `p` tab completion for switching to Project directories
for item in ~/Projects/*; do
  if [ -d "$item" ] ; then
    # Extract the folder name
    # could also be name=${item##*/}
    name=$(basename $item)
    COMPLETE_LIST+="$name "
  fi
done
unset item
complete -o "nospace" -W "$COMPLETE_LIST" p
unset COMPLETE_LIST

# Add tab completion for SSH hostnames based on ~/.ssh/config, ignoring wildcards
[ -e "$HOME/.ssh/config" ] && complete -o "default" -o "nospace" -W "$(grep "^Host" ~/.ssh/config | grep -v "[?*]" | cut -d " " -f2 | tr ' ' '\n')" scp sftp ssh

# Autocomplete Grunt commands
which grunt &> /dev/null && eval "$(grunt --completion=bash)"

# Colon-separated list of directories in which the shell looks for destination directories specified by the cd command.
CDPATH=".:~:/private"

# Enable some Bash 4 features when possible:
# * `autocd`, e.g. `**/qux` will enter `./foo/bar/baz/qux`
# * Recursive globbing, e.g. `echo **/*.txt`
for option in autocd globstar; do
  shopt -s "$option" 2> /dev/null
done

# Case-insensitive globbing (used in pathname expansion)
shopt -s nocaseglob

# Append to the Bash history file, rather than overwriting it
shopt -s histappend

# Autocorrect typos in path names when using `cd`
shopt -s cdspell
